In [44]:
from tensorflow.keras.preprocessing.text import one_hot

In [45]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [46]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [47]:
### Define the Vocab size
vocab_size = 10000

In [48]:
# One hot representation 

one_hot_repr = [one_hot(words, vocab_size)for words in sent]
one_hot_repr

[[379, 6171, 1079, 5643],
 [379, 6171, 1079, 228],
 [379, 3525, 1079, 2382],
 [3457, 4267, 7293, 8408, 7735],
 [3457, 4267, 7293, 8408, 7401],
 [3977, 379, 728, 1079, 6905],
 [350, 8820, 9748, 8408]]

In [49]:
# WOrd Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [50]:
import numpy as np

In [51]:
sent_len = 8

In [52]:
embedded_docs = pad_sequences(
    one_hot_repr,
    maxlen=sent_len,
    padding='pre',
)
embedded_docs

array([[   0,    0,    0,    0,  379, 6171, 1079, 5643],
       [   0,    0,    0,    0,  379, 6171, 1079,  228],
       [   0,    0,    0,    0,  379, 3525, 1079, 2382],
       [   0,    0,    0, 3457, 4267, 7293, 8408, 7735],
       [   0,    0,    0, 3457, 4267, 7293, 8408, 7401],
       [   0,    0,    0, 3977,  379,  728, 1079, 6905],
       [   0,    0,    0,    0,  350, 8820, 9748, 8408]], dtype=int32)

In [53]:
# Feature Representation 
dim = 10

In [54]:
model = Sequential()
model.add(Embedding(vocab_size, dim,input_length = sent_len ))
model.compile('adam', 'mse')

d:\Projects\RNN_IMDB\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [55]:
model.build(input_shape=(None, sent_len))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.02756782,  0.04056691,  0.00229017, -0.03400703,
          0.02838599,  0.01366304,  0.01064764,  0.00086055,
          0.0494757 ,  0.02276481],
        [-0.01476506, -0.00215545, -0.03642436,  0.04775006,
          0.03203282,  0.04509398, -0.04307858, -0.02129838,
          0.01841313,  0.02431205],
        [ 0.00072747,  0.0261161 ,  0.04388702, -0.0

In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,  379, 6171, 1079, 5643], dtype=int32)

In [61]:
model.predict(np.expand_dims(embedded_docs[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


array([[[-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.01591203, -0.03043052, -0.03662683, -0.01549812,
         -0.01980509,  0.01516681,  0.02367672, -0.01443259,
         -0.01027055,  0.0027684 ],
        [-0.02756782,  0.04056691,  0.00229017, -0.03400703,
          0.02838599,  0.01366304,  0.01064764,  0.00086055,
          0.0494757 ,  0.02276481],
        [-0.01476506, -0.00215545, -0.03642436,  0.04775006,
          0.03203282,  0.04509398, -0.04307858, -0.02129838,
          0.01841313,  0.02431205],
        [ 0.00072747,  0.0261161 ,  0.04388702, -0.0